# Generated by Django 5.2.17 on 2026-08-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bio',
            field=models.TextField(max_length=280),
        ),
    ]
